### ISSUE TITLE
:bug: Bug - gpt 한테 요청보낼때 400에러 나는 현상

### ISSUE THREAD

**Issue by codesejin** [team-opensource-plus/dummy-generator#8]
### 🐛 Summary

개인 프로젝트 내에서는 요청과 응답이 잘 작동하는데,
코드 옮겨와서 시도해보니까 400에러가 발생합니다
혹시 몰라서 apiKey도 새로 발급받아서 적용해봤는데 동일한 이슈가 발생합니다.

[개인 레포 커밋 내용 - src/app.service.ts ](https://github.com/codesejin/nest-openai-chat/commit/41259ff)
[팀플 커밋 내용 - src/dummy.js](https://github.com/team-opensource-plus/dummy-generator/commit/c511add)

동일한 코드

```
      const chat_completion = await openai.createChatCompletion({
          // chat-gpt 언어 모델
          model: "text-davinci-003",
          // 프롬프트 명령어
          prompt: prompt,
          // 정직한 답변은 0, 상상력 발휘하기 원하면 2 이상
          temperature: 0,
          // 1024가 설정 기본값, 이상을 넘어가면 과금
          max_tokens: 1000,
          top_p: 1,
          frequency_penalty: 0.0,
          presence_penalty: 0.0,
          stop: ["\n"],
      });
```

### 📝 Steps to Reproduce

1. root 경로에서 src 로 이동 
( 이유 : 루트경로에서 cli 명령어를 칠 경우 `Cannot find module '/Users/sejinpark/workspace/opensource/dummy-generator/dummy.js` 에러가 나기 때문)
2. `node dummy.js g -f ../samples/user-data-config.json -o json` cli 명령어 입력
3. 파일을 읽어오는거 까지 되는데, gpt한테 전송할때 400 Bad Request 응답 나옴
4. `Error: Request failed with status code 400`

### 💭 Expected Behavior

동일한 코드로 개인 프로젝트에서 api 요청 보낼때는 정상 응답이 되어서 파일도 새로 저장됩니다. 
아래 스크린샷에서 보시면 `dummy_2.json` 이라는 파일이 새로 생겨서 초록 불인 것을 볼 수 있습니다.

### 🐞 Actual Behavior

`node dummy.js g -f ../samples/user-data-config.json -o json` cli 명령어 입력
( 특정 부분부터 로그가 2개씩 나오는 것도 신경쓰입니다)

```
sejinpark@Sejins-MacBook-Pro src % node dummy.js g -f ../samples/user-data-config.json -o json

options.file : ../samples/user-data-config.json
configFilePath : /Users/sejinpark/workspace/opensource/dummy-generator/samples/user-data-config.json
columns : [object Object],[object Object]
prompt : 나는 인공지능 AI Chatbot이야. 질문을 하면 내가 답변을 해줄께. 만약 모른다면 "모름"이라고 할께.
      

Q: [{"column-name":"name","column-description":"한국사람이름","max-length":"3","unique":true},{"column-name":"age","column-description":"나이","max-length":"2","unique":false}] 해당 data-config 를 보고 임시 데이터 10개를 json 형식으로 만들어줘
      A:
options.file : ../samples/user-data-config.json
configFilePath : /Users/sejinpark/workspace/opensource/dummy-generator/samples/user-data-config.json
columns : [object Object],[object Object]
prompt : 나는 인공지능 AI Chatbot이야. 질문을 하면 내가 답변을 해줄께. 만약 모른다면 "모름"이라고 할께.
      

Q: [{"column-name":"name","column-description":"한국사람이름","max-length":"3","unique":true},{"column-name":"age","column-description":"나이","max-length":"2","unique":false}] 해당 data-config 를 보고 임시 데이터 10개를 json 형식으로 만들어줘
      A:
Error: Request failed with status code 400
Error: Request failed with status code 400
```

개인 프로젝트와의 차이점이라면 gpt 요청이 commander 내부에 있고 없고 차이인 것 같습니다

### 🌍 Environment

운영체제 : Mac os
IDE : vsCode

### 📸 Screenshots

> 개인 프로젝트에서의 응답

![image](https://github.com/team-opensource-plus/dummy-generator/assets/101460733/1f370633-c792-42a5-aed0-4405dc0808c6)

> 팀 프로젝트에서 코드를 옮겨와서 시도 했을때 응답

<img width="1361" alt="image" src="https://github.com/team-opensource-plus/dummy-generator/assets/101460733/3c12d7a6-5d87-467d-ab2b-05f4df1f1b5e">

**Comment by pyuseon** [comment]
`  const chat_completion = await openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      messages: [{role: "user", content: prompt}],
    });`

`const chat_completion = await openai.createCompletion(
        {
          model: "text-davinci-003",
          prompt: prompt,
        },
        {
          timeout: 10000,
          headers: {
            "Example-Header": "example",
          },
        }
      );`

위 두 요청이 가는 것을 보니 리퀘스트 양식을 고치면 갈 것 같아요 ! 
위 코드는 주석 처리해서 올려 두었으니 확인 부탁드려요 !

**Comment by codesejin** [comment]
아하~!!! `openai.createChatCompletion` 랑 `openai.createCompletion` 랑 서로 요청값이 다른데, 기존꺼랑 사용하던 라이브러리가 달랐네요 ㅋㅋㅋㅋ 이해했습니다 너무 감사합니당 ❤️
